# Generated by Django 5.1.2 on 2024-10-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="point",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
