# Generated by Django 5.1.2 on 2024-10-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0002_alter_point_city_alter_point_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="point",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="point_images/"),
        ),
    ]
